--- 
title: "Term project draft"
author: "Kipling Klimas"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is the term project for WILD6900 spring 2021."
---

# Introduction

This project is focused on the relationship between a variety of environmental, topographic and derived variables and burn severity data for forest and non-forest environments in Utah.  

Burn severity is a measure of ecological change after wildfire, commonly assessed in terms of vegetation mortality or biomass loss,
and is burn severity data is easily collected through remote sensing. Burn severity data is available from the The Monitoring Trends in Burn Severity (MTBS) databas, which containes burn severity data for wildfires >1000 acres across the continental US. 
These data are available in the form of spatially explicit raster layers with continuous and categorical burn severity layers. 

The database used in this project contains fire behavior, structure, topographic, risk and vegetation 'predictor' variables for both
forest and non-forest land along with burn severity data. 

## Project goals

The specific goal of this project is to vizualize the relationship between burn severity and a variety of environmental variables in forest and non-forest enviornments. This includes creating plots that show:

1. Burn severity vs. elevation
2. Burn severity vs. canopy categories
3. Burn severity vs. Vegetation type
4. Burn severity vs. elevation with risk and canopy variables overlayed

## Project outline

The book is composed of the following chapters:

* Chapter 1: data description and structure
* Chapter 2: database creation
* Chapter 3: database connection'
* Chapter 4: forest data visualization 
* Chapter 5: non-forest data visualization






```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
